title: IT 찍먹러
description: > # this means to ignore newlines until "baseurl:"
  부먹도 존중하는 IT 개발자 지망생<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dieglory.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#remote_theme : kaptn3/future-imperfect


author:
  name: 'Gunwoo'
  last_name: 'Han'
  cv: '//github.com/DieGlory/DieGlory'
  avatar: '/images/avatar.jpeg'
  github_username:  DieGlory 
  email: aya02245@naver.com
#  vk_id: id201664979
#  telegram_name: vikapitoshka 
  logo: '/images/logo-pickaxe.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


